---
title: "Music Insights"
author: "Asheela Magwili"
output:
  html_document:
    df_print: paged
---

```{r}
library("tidyverse")
library("dplyr")
library("tidyr")
library("readr")

survey <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/music-survey.csv")
preferences <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/preferences-survey.csv")
```

# Cleaning Variable Names
```{r}
colnames(survey)[colnames(survey) == "Timestamp"] <- "time_submitted"

colnames(survey)[colnames(survey) == "First, we are going to create a pseudonym for you to keep this survey anonymous (more or less). Which pseudonym generator would you prefer?"] <- "pseudonym_generator"

colnames(survey)[colnames(survey) == "What is your pseudonym?"] <- "pseudonym"

colnames(survey)[colnames(survey) == "Which musical instruments/talents do you play? (Select all that apply)"] <- "instrument_list"

colnames(survey)[colnames(survey) == "Major"] <- "academic_major"

colnames(survey)[colnames(survey) == "Year you were born (YYYY)"] <- "year_born"

colnames(survey)[colnames(survey) == "Artist"] <- "favorite_song_artist"

colnames(survey)[colnames(survey) == "Link to song (on Youtube or Vimeo)"] <- "favorite_song_link"

colnames(survey)[colnames(survey) == "Sex"] <- "sex"

colnames(survey)[colnames(survey) == "Academic Year"] <- "academic_level"

colnames(survey)[colnames(survey) == "Song"] <- "favorite_song"

colnames(survey)
```

# Creating Tables
```{r}
Person <- tibble(time_submitted = survey$time_submitted, pseudonym = survey$pseudonym, sex = survey$sex, academic_major = survey$academic_major, academic_level = survey$academic_level, year_born = survey$year_born)

FavoriteSong <- tibble(pseudonym = survey$pseudonym, artist = survey$favorite_song_artist, song = survey$favorite_song, link = survey$favorite_song_link)
```

# Cleaning Data
```{r}
Person$time_submitted <- as.POSIXlt(parse_datetime(Person$time_submitted, format="%m/%d/%y %H:%M"))
```


Cleaning academic major's levels by making the letter cases more consistent:
```{r}
Person$academic_major <- as.factor(Person$academic_major)
levels(Person$academic_major)[levels(Person$academic_major) == "Computer information systems"] <- "Computer Information Systems"

levels(Person$academic_major)
```

# Create a 'Rating' Table
Create a Ratings table using the R function gather()
```{r}
preferences$Timestamp <- NULL
Rating <- gather(preferences,artist_song,rating,"40 crew\tNot Enough" :"Wheezer\tBuddy Holly")
Rating <- tibble(pseudonym = Rating$`What was your pseudonym?`, artist_song = Rating$artist_song, rating = Rating$rating)
```